# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3866f8e91ebddd61b3fc95f08c363955b6c7e9a6483bba6242d84c23dad02fad0da9fbde14ee75808b30d5673e4ac1a1dbe9246368052e10e08c89a6d87efc3

test:
  secret_key_base: 9d8a37be0cab3319fcbb549759725e61339bd13ac5e5b405e0c483d39aee387d329cb5ec00a879fd7173b7bf2605436077de4981d7fbe43461fbb4f89a2cd799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
